language: objective-c
osx_image: xcode7.3
branches:
  only:
  - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Max.xcodeproj
  - IOS_FRAMEWORK_SCHEME="Max iOS"
  - OSX_FRAMEWORK_SCHEME="Max macOS"
  - TVOS_FRAMEWORK_SCHEME="Max tvOS"
  - IOS_SDK=iphonesimulator9.3
  - OSX_SDK=macosx10.11
  - TVOS_SDK=appletvsimulator9.2
 matrix:
  - DESTINATION="OS=9.2,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES"
  - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES"
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- if [ $RUN_TESTS == "YES" ]; then xcodebuild -project "$PROJECT" -scheme "$SCHEME"
  -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO
  test | xcpretty -c; else xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK"
  -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty
  -c; fi
  
- if [ $RUN_TESTS == "YES" ]; then xcodebuild -project "$PROJECT" -scheme "$SCHEME"
  -sdk "$SDK" -destination "$DESTINATION" -configuration Release ENABLE_TESTABILITY=YES
  ONLY_ACTIVE_ARCH=NO test | xcpretty -c; else xcodebuild -project "$PROJECT" -scheme
  "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO
  build | xcpretty -c; fi
